//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hacienda.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hacienda.WebApi.Resources.WebApiResources", typeof(WebApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string WebApi_Contacto {
            get {
                return ResourceManager.GetString("WebApi_Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ejemplo.com/contacto.
        /// </summary>
        public static string WebApi_ContactoUrl {
            get {
                return ResourceManager.GetString("WebApi_ContactoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción para qué sirve esta web API.
        /// </summary>
        public static string WebApi_Descripcion {
            get {
                return ResourceManager.GetString("WebApi_Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencia de uso.
        /// </summary>
        public static string WebApi_Licencia {
            get {
                return ResourceManager.GetString("WebApi_Licencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ejemplo.com/licencia.
        /// </summary>
        public static string WebApi_LicenciaUrl {
            get {
                return ResourceManager.GetString("WebApi_LicenciaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ejemplo.com/terminos.
        /// </summary>
        public static string WebApi_TerminosLicenciaUrl {
            get {
                return ResourceManager.GetString("WebApi_TerminosLicenciaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de la API de producto.
        /// </summary>
        public static string WebApi_Titulo {
            get {
                return ResourceManager.GetString("WebApi_Titulo", resourceCulture);
            }
        }
    }
}
