//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Htn.Infrastructure.Global.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Htn.Infrastructure.Global.Resources.Global.Resources", typeof(Global_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo una excepción no controlada..
        /// </summary>
        public static string MsgExcepcionNoControlada {
            get {
                return ResourceManager.GetString("MsgExcepcionNoControlada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha podido realizar la operación..
        /// </summary>
        public static string MsgOperacionKo {
            get {
                return ResourceManager.GetString("MsgOperacionKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación incompleta..
        /// </summary>
        public static string MsgOperacionKoTitulo {
            get {
                return ResourceManager.GetString("MsgOperacionKoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La operación se ha realizado con éxito..
        /// </summary>
        public static string MsgOperacionOk {
            get {
                return ResourceManager.GetString("MsgOperacionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación completa..
        /// </summary>
        public static string MsgOperacionOkTitulo {
            get {
                return ResourceManager.GetString("MsgOperacionOkTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha encontrado el recurso que se busca..
        /// </summary>
        public static string MsgRecursoNoEncontrado {
            get {
                return ResourceManager.GetString("MsgRecursoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El elemento a validar contiene errores:.
        /// </summary>
        public static string MsgValidacionKo {
            get {
                return ResourceManager.GetString("MsgValidacionKo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validación incorrecta..
        /// </summary>
        public static string MsgValidacionKoTitulo {
            get {
                return ResourceManager.GetString("MsgValidacionKoTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
